function(install_if_not_exists src dest)
  set(real_dest "${dest}")
  if(NOT IS_ABSOLUTE "${src}")
    set(src "${CMAKE_CURRENT_SOURCE_DIR}/${src}")
  endif()
  get_filename_component(src_name "${src}" NAME)
  get_filename_component(basename_dest "${src}" NAME)
  string(REPLACE "/" "\\\\" nsis_src "${src}")
  string(REPLACE "/" "\\\\" nsis_dest_dir "${real_dest}")
  string(REPLACE "/" "\\\\" nsis_dest "${real_dest}/${basename_dest}")
  install(CODE "
   if(\"\$ENV{DESTDIR}\" STREQUAL \"\")
      set(target_dir \${CMAKE_INSTALL_FULL_SYSCONFDIR})
    else()
      set(target_dir \$ENV{DESTDIR})
    endif()
    if(\${CMAKE_INSTALL_FULL_PREFIX} MATCHES .*/_CPack_Packages/.* OR NOT EXISTS \"\$ENV{DESTDIR}\${CMAKE_INSTALL_FULL_SYSCONFDIR}/\${skel_prefix}${dest}/${src_name}\")
      message(STATUS \"Installing: \$ENV{DESTDIR}${dest}/${src_name}\")
      if(\${CMAKE_INSTALL_FULL_PREFIX} MATCHES .*/_CPack_Packages/.*)
        set(skel_prefix \"share/skel/\")
      else()
        set(skel_prefix \"\")
      endif()
      execute_process(COMMAND \${CMAKE_COMMAND} -E copy \"${src}\"
                      \"\${target_dir}/\${skel_prefix}${dest}/${src_name}\"
                      RESULT_VARIABLE copy_result
                      ERROR_VARIABLE error_output)
      if(copy_result)
        message(FATAL_ERROR \${error_output})
      endif()
    else()
      message(STATUS \"Skipping  : \${target_dir}/${dest}/${src_name}\")
    endif()
  ")
endfunction()
